version: '3.7'

services:
    postservice:
        build: .
        image: postservice:0.0.1
        ports:
            - 8081:8080
        depends_on:
            - postgres
            - redis
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/posts
            - SPRING_REDIS_HOST=redis

    postgres:
        image: postgres:12.2-alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_DB: posts
            POSTGRES_USER: postservice
            POSTGRES_PASSWORD: secretDbPassword
        volumes:
            - type: bind
              source: ./etc/init_db.sql
              target: /docker-entrypoint-initdb.d/init_db.sql
              read_only: true

    redis:
        image: redis:5.0.8-alpine
        ports:
            - '6379:6379'
